# Generated by Django 4.0.1 on 2022-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_destination_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_STD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
